# Generated by Django 4.1.7 on 2023-05-25 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachertablestructure',
            name='content_access',
        ),
    ]
