# Generated by Django 4.1.7 on 2023-06-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0002_remove_teachertablestructure_content_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttablestructure',
            name='admission_number',
        ),
        migrations.RemoveField(
            model_name='studenttablestructure',
            name='app_token',
        ),
        migrations.RemoveField(
            model_name='studenttablestructure',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='studenttablestructure',
            name='birthplace',
        ),
        migrations.RemoveField(
            model_name='studenttablestructure',
            name='caste',
        ),
        migrations.RemoveField(
            model_name='studenttablestructure',
            name='mode_of_transport',
        ),
        migrations.RemoveField(
            model_name='studenttablestructure',
            name='mother_tongue',
        ),
        migrations.RemoveField(
            model_name='studenttablestructure',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='studenttablestructure',
            name='permanent_registration_number',
        ),
        migrations.RemoveField(
            model_name='studenttablestructure',
            name='school_house',
        ),
        migrations.RemoveField(
            model_name='studenttablestructure',
            name='sub_cast',
        ),
        migrations.RemoveField(
            model_name='teachertablestructure',
            name='avatar',
        ),
        migrations.AddField(
            model_name='gradetablestructure',
            name='student',
            field=models.ManyToManyField(to='projectApp.studenttablestructure'),
        ),
        migrations.AddField(
            model_name='gradetablestructure',
            name='teacher',
            field=models.ManyToManyField(to='projectApp.teachertablestructure'),
        ),
        migrations.AlterField(
            model_name='gradetablestructure',
            name='updateddate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='questiontablestructure',
            name='updateddate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='studenttablestructure',
            name='updateddate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='teachertablestructure',
            name='updateddate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
